# Generated by Django 3.2.3 on 2021-05-22 03:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9)]),
        ),
    ]
