# Generated by Django 3.2.3 on 2021-05-22 04:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_users_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999999999)]),
        ),
    ]
